language: python
sudo: false
branches:
only:
    - master
python:
    - 3.5
    - 3.6

before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p ./miniconda
    - export PATH=`pwd`/miniconda/bin:$PATH
    - conda update --yes conda
    - conda create -y -q -n test-env python=$TRAVIS_PYTHON_VERSION 
    - source activate test-env
    - conda install -y numpy scipy pandas six pip requests pytest
    - pip install -r requirements.txt
    - python -c 'import requests; print(requests.__version__)'
    - python -c 'import pandas; print(pandas.__version__)'
    - python -c 'import cenpy; print(cenpy.__version__)'

install:
    - python setup.py install

script:
    - python setup.py sdist > /dev/null
    - pytest cenpy/
 
notifications:
    email:
        recipients:
            - levi.john.wolf@gmail.com
        on_success: change
        on_faliure: always
